### ISSUE TITLE
ERROR:  date/time field value out of range: "1478362007"

### ISSUE THREAD

**Issue by eemeli** [voxpelli/node-connect-pg-simple#38]
`3.1.1` and in particular bd6d3a2 appears to have broken sessions for me, causing the error in the title on all connections (with a changing timestamp, obviously).

This is on a dockerised app (node 6.9.1, express 4.14.0, express-session 1.14.2) connecting to Postgres 9.5.5. I'm using connect-pg-simple [here](/worldcon75/api/blob/master/kansa/server/app.js#L8), with [this](/worldcon75/api/blob/master/postgres/init/10-admin-init.sql#L11) Postgres table config.

**Comment by voxpelli** [comment]
Should be fixed in `3.1.2` thanks to PR #39

**Comment by EvgeniyRRU** [comment]
It seems, problem still relevant on `node 14.19` and `postgres 11.4`.

**Comment by voxpelli** [comment]
@EvgeniyRRU If so: Open a new issue + preferably show some code that reproduces the error
